// src/templates/python.ts
export const pythonTemplate = [
  { 
    path: 'main.py', 
    content: 'def main():\n    print("Hello, Nova Code!")\n\nif __name__ == "__main__":\n    main()\n' 
  },
  { 
    path: 'README.md', 
    content: '# My Python Project\n\nGenerated by Nova Code.\n' 
  },
];